### ISSUE TITLE
issue with assets from solidus

### ISSUE THREAD

**Issue by harin** [refinerycms-contrib/solidus-refinery-authentication#1]
When I visit the solidus admin page, I get 
`Asset filtered out and will not be served: add 'Rails.application.config.assets.precompile += %w( select2-spinner.gif )' to 'config/initializers/assets.rb' and restart your server`

At first I get this message for `select2.png` but when I add this one, another one pops up. So I'm guess that this applies to all the precompile assets that solidus adds to the list.

**Comment by bricesanchez** [comment]
I think your error is related to https://github.com/solidusio/solidus/pull/605
